name: Python application

on:
  push:
    branches: [ "main", "master" ] # Add other branches if needed, e.g., "develop"
  pull_request:
    branches: [ "main", "master" ] # Add other branches if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Specify a specific version if your project requires it, e.g., '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run application script
      run: python movie_app.py 